carts/urls.py
from django.urls import path
from .views import cart_home, cart_update, checkout_home, checkout_done_view

app_name = 'carts'
urlpatterns =[
    path('', cart_home, name='home'),
    path('checkout', checkout_home, name='checkout'),
    path('update', cart_update, name='update'),
    path('checkout/success/', checkout_done_view, name='success')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register, guest_register_view
from .views import home, contact, about
from addresses.views import checkout_Address_create_view, checkout_Address_use_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('login/', login_page, name='login'),
    path('register/guest', guest_register_view, name='guest_register'),
    path('register/', register, name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('checkout/address/create/', checkout_Address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_Address_use_view, name='checkout_address_reuse'),
    path('products/', include("products.urls", namespace='products')),
    path('search/', include("search.urls", namespace='search')),
    path('cart/', include("carts.urls", namespace='carts')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from decimal import Decimal
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, post_save, m2m_changed

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id",None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count()==1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new_cart(user=request.user)
            new_obj = True
            request.session["cart_id"] = cart_obj.id
        return cart_obj, new_obj

    def new_cart(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = CartManager()

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    instance.total = 0
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)

pre_save.connect(pre_save_cart_receiver, sender=Cart)
    

carts/views.py
from django.shortcuts import render, redirect
from products.models import Product
from .models import Cart
from orders.models import Order
from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from billing.models import BillingProfile
from addresses.forms import AddressForm
from addresses.models import Address

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, 'carts/home.html', {"cart": cart_obj})

def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
                return redirect("carts:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session["cart_items"] = cart_obj.products.count()
    return redirect("carts:home")

def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0 :
        return redirect("cart:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        shipping_address_qs = address_qs.filter(address_type='shipping')
        billing_address_qs = address_qs.filter(address_type='billing')
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            del request.session["shipping_address_id"]
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
        if billing_address_id:
            del request.session["billing_address_id"]
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_done()
            request.session['cart_items']=0
            del request.session["cart_id"]
            return redirect("carts:success")

    context = {
        "object": order_obj,
        "billing_profile": billing_profile, 
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs

    }
    return render(request, "carts/checkout.html", context)

def checkout_done_view(request):
    return render(request, "carts/checkout-done.html")

carts/templates/carts/checkout-done.html
{% extends "base.html" %}

{% block content %}

<div class='col-6 mx-auto py-5 text-center'>
    <h1 class='idsplay-1'>Thank you for your order!</h1>

</div>

{% endblock %}

carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content%}

{% if not billing_profile %}
<div class='row text-center'>
    <div class='col-12 col-md-6'>
        <p class='lead'>Login</p>
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
    </div>
    <div class='col-12 col-md-6'>
        Continue as Guest

        {% url "guest_register" as guest_register_url %}
        {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri
        action_url=guest_register_url %}
    </div>

</div>

{% else %}

{% if not object.shipping_address %}
<div class='row'>
        <div class='col-12'>
            <p class='lead'>Shipping Address</p>
            <hr />
        </div>   
        <div class='col-6'>
                {% url "checkout_address_create" as checkout_address_create_url %}
                {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create_url address_type='shipping' %}
            </div>
            <div class='col-6'>
                {% url 'checkout_address_reuse' as checkout_address_reuse %}
                {% include 'addresses/prev-addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
            </div>
        </div>


{% elif not object.billing_address %}
<div class='row'>
    <div class='col-12'>
        <p class='lead'>Billing Address</p>
        <hr />
    </div>
    <div class='col-6'>
        {% url "checkout_address_create" as checkout_address_create_url %}
        {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create_url address_type='billing' %}
    </div>
    <div class='col-6'>
        {% url 'checkout_address_reuse' as checkout_address_reuse %}
        {% include 'addresses/prev-addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse %}
    </div>
</div>

{% else %}

<h1>Checkout</h1>
<p>Cart Items: {% for product in object.cart.products.all %} {{ product }} {% if not forloop.last %}, {% endif %} {% endfor %}</p>
<p>Shipping Address: {{ object.shipping_address.get_address }}</p>
<p>Billing Address: {{ object.billing_address.get_address }}</p>
<p>Cart Total: {{ object.cart.total }}</p>
<p>Shipping Total: {{ object.shipping_total }}</p>
<p>Order Total: {{ object.order_total }}</p>
<form class='form' method='POST' action="">{% csrf_token %}
    <button class='btn btn-success' type='submit'>Checkout</button>
</form>

{% endif %}
{% endif %}

{% endblock %}

carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}

<h1>Cart</h1>

{% if cart.products.exists %}

<table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody>
            {%for product in cart.products.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                {% include 'products/snippets/update-cart.html' with object=product cart=cart in_cart=True %}

            </td> 
            <td>{{ product.price }}</td>
          </tr>
            {% endfor %}
          <tr>
            <td colspan="2"></td>
            <td><b>Subtotal</b> {{ cart.subtotal }}</td>
          </tr>
          <tr>
             <td colspan="2"></td>
             <td><b>Total</b> {{ cart.total }}</td>
          </tr>
          <tr>
            <td colspan="2>"></td>
            <td><a class='btn btn-lg btn-success' href="{% url "carts:checkout" %}">Checkout</a></td>
          </tr>
        </tbody>
      </table>

{% else %}
<p class='lead'>Cart is empty!</p>
{%endif%}

{% endblock %}